const initialEmployees = [
    {
      id: 1,
      name: "John Doe",
      email: "johndoe@example.com", 
      position: "Software Engineer",
      startDate: "2022-01-01",
      leaveBalance: 15,
      performanceReport: "Excellent performance in Q4 2024.",
    },
    {
      id: 2,
      name: "Jane Smith",
      email: "janesmith@example.com",
      position: "HR Manager", 
      startDate: "2021-05-15",
      leaveBalance: 10,
      performanceReport: "Consistent performance throughout 2024.",
    },
    {
      id: 3,
      name: "Michael Johnson",
      email: "mjohnson@example.com",
      position: "Product Manager",
      startDate: "2021-08-20",
      leaveBalance: 12,
      performanceReport: "Strong leadership skills shown in 2024.",
    },
    {
      id: 4,
      name: "Sarah Williams",
      email: "swilliams@example.com",
      position: "UX Designer",
      startDate: "2022-03-15",
      leaveBalance: 18,
      performanceReport: "Creative solutions delivered consistently.",
    },
    {
      id: 5,
      name: "Robert Brown",
      email: "rbrown@example.com",
      position: "Senior Developer",
      startDate: "2021-02-10",
      leaveBalance: 8,
      performanceReport: "Key contributor to major projects.",
    },
    {
      id: 6,
      name: "Emily Davis",
      email: "edavis@example.com",
      position: "Marketing Specialist",
      startDate: "2022-06-01",
      leaveBalance: 20,
      performanceReport: "Exceeded marketing campaign goals.",
    },
    {
      id: 7,
      name: "James Wilson",
      email: "jwilson@example.com",
      position: "System Administrator",
      startDate: "2021-11-30",
      leaveBalance: 14,
      performanceReport: "Maintained 99.9% system uptime.",
    },
    {
      id: 8,
      name: "Lisa Anderson",
      email: "landerson@example.com",
      position: "Financial Analyst",
      startDate: "2022-04-15",
      leaveBalance: 16,
      performanceReport: "Accurate financial forecasting.",
    },
    {
      id: 9,
      name: "David Martinez",
      email: "dmartinez@example.com",
      position: "Sales Manager",
      startDate: "2021-07-01",
      leaveBalance: 11,
      performanceReport: "Exceeded sales targets by 25%.",
    },
    {
      id: 10,
      name: "Jennifer Taylor",
      email: "jtaylor@example.com",
      position: "Content Writer",
      startDate: "2022-02-28",
      leaveBalance: 19,
      performanceReport: "High-quality content delivery.",
    },
    {
      id: 11,
      name: "Thomas Moore",
      email: "tmoore@example.com",
      position: "QA Engineer",
      startDate: "2021-09-15",
      leaveBalance: 13,
      performanceReport: "Improved testing processes.",
    },
    {
      id: 12,
      name: "Patricia White",
      email: "pwhite@example.com",
      position: "HR Specialist",
      startDate: "2022-01-20",
      leaveBalance: 17,
      performanceReport: "Excellent employee relations.",
    },
    {
      id: 13,
      name: "Kevin Lee",
      email: "klee@example.com",
      position: "Mobile Developer",
      startDate: "2021-06-10",
      leaveBalance: 9,
      performanceReport: "Launched successful mobile app.",
    },
    {
      id: 14,
      name: "Michelle Garcia",
      email: "mgarcia@example.com",
      position: "Project Coordinator",
      startDate: "2022-05-01",
      leaveBalance: 21,
      performanceReport: "Efficient project management.",
    },
    {
      id: 15,
      name: "Christopher Clark",
      email: "cclark@example.com",
      position: "Data Analyst",
      startDate: "2021-12-15",
      leaveBalance: 15,
      performanceReport: "Valuable data insights provided.",
    },
    {
      id: 16,
      name: "Amanda Rodriguez",
      email: "arodriguez@example.com",
      position: "Customer Support",
      startDate: "2022-03-30",
      leaveBalance: 18,
      performanceReport: "High customer satisfaction ratings.",
    },
    {
      id: 17,
      name: "Daniel Lewis",
      email: "dlewis@example.com",
      position: "DevOps Engineer",
      startDate: "2021-08-01",
      leaveBalance: 12,
      performanceReport: "Streamlined deployment processes.",
    },
    {
      id: 18,
      name: "Laura Hall",
      email: "lhall@example.com",
      position: "Graphic Designer",
      startDate: "2022-07-15",
      leaveBalance: 20,
      performanceReport: "Creative design solutions.",
    },
    {
      id: 19,
      name: "Steven Young",
      email: "syoung@example.com",
      position: "Business Analyst",
      startDate: "2021-04-20",
      leaveBalance: 14,
      performanceReport: "Thorough business analysis.",
    },
    {
      id: 20,
      name: "Maria Lopez",
      email: "mlopez@example.com",
      position: "Office Manager",
      startDate: "2022-01-10",
      leaveBalance: 16,
      performanceReport: "Efficient office operations.",
    },
    {
      id: 21,
      name: "Richard Turner",
      email: "rturner@example.com",
      position: "Software Engineer",
      startDate: "2021-10-05",
      leaveBalance: 11,
      performanceReport: "Strong technical skills.",
    },
    {
      id: 22,
      name: "Karen Phillips",
      email: "kphillips@example.com",
      position: "Marketing Manager",
      startDate: "2022-04-01",
      leaveBalance: 19,
      performanceReport: "Successful marketing strategies.",
    },
    {
      id: 23,
      name: "Joseph Scott",
      email: "jscott@example.com",
      position: "IT Support",
      startDate: "2021-07-20",
      leaveBalance: 13,
      performanceReport: "Prompt technical support.",
    },
    {
      id: 24,
      name: "Sandra Adams",
      email: "sadams@example.com",
      position: "Account Manager",
      startDate: "2022-02-15",
      leaveBalance: 17,
      performanceReport: "Strong client relationships.",
    },
    {
      id: 25,
      name: "George Baker",
      email: "gbaker@example.com",
      position: "Frontend Developer",
      startDate: "2021-05-30",
      leaveBalance: 10,
      performanceReport: "Excellent UI implementations.",
    },
    {
      id: 26,
      name: "Betty Nelson",
      email: "bnelson@example.com",
      position: "HR Coordinator",
      startDate: "2022-06-15",
      leaveBalance: 21,
      performanceReport: "Effective HR programs.",
    },
    {
      id: 27,
      name: "Paul Carter",
      email: "pcarter@example.com",
      position: "Backend Developer",
      startDate: "2021-11-01",
      leaveBalance: 15,
      performanceReport: "Robust backend solutions.",
    },
    {
      id: 28,
      name: "Margaret Mitchell",
      email: "mmitchell@example.com",
      position: "Content Manager",
      startDate: "2022-03-01",
      leaveBalance: 18,
      performanceReport: "Quality content strategy.",
    },
    {
      id: 29,
      name: "Kenneth Roberts",
      email: "kroberts@example.com",
      position: "Systems Analyst",
      startDate: "2021-08-15",
      leaveBalance: 12,
      performanceReport: "Improved system efficiency.",
    },
    {
      id: 30,
      name: "Helen Torres",
      email: "htorres@example.com",
      position: "UX Researcher",
      startDate: "2022-07-01",
      leaveBalance: 20,
      performanceReport: "Valuable user insights.",
    },
    {
      id: 31,
      name: "Frank Morgan",
      email: "fmorgan@example.com",
      position: "Sales Representative",
      startDate: "2021-04-01",
      leaveBalance: 14,
      performanceReport: "Consistent sales performance.",
    },
    {
      id: 32,
      name: "Carol Murphy",
      email: "cmurphy@example.com",
      position: "Technical Writer",
      startDate: "2022-01-15",
      leaveBalance: 16,
      performanceReport: "Clear technical documentation.",
    },
    {
      id: 33,
      name: "Raymond Cooper",
      email: "rcooper@example.com",
      position: "Product Designer",
      startDate: "2021-10-20",
      leaveBalance: 11,
      performanceReport: "Innovative design solutions.",
    },
    {
      id: 34,
      name: "Sharon Reed",
      email: "sreed@example.com",
      position: "Operations Manager",
      startDate: "2022-04-10",
      leaveBalance: 19,
      performanceReport: "Streamlined operations.",
    },
    {
      id: 35,
      name: "Jerry Howard",
      email: "jhoward@example.com",
      position: "Network Engineer",
      startDate: "2021-07-05",
      leaveBalance: 13,
      performanceReport: "Reliable network maintenance.",
    },
    {
      id: 36,
      name: "Diane Wood",
      email: "dwood@example.com",
      position: "Digital Marketing",
      startDate: "2022-02-01",
      leaveBalance: 17,
      performanceReport: "Effective digital campaigns.",
    },
    {
      id: 37,
      name: "Roger Price",
      email: "rprice@example.com",
      position: "Software Architect",
      startDate: "2021-05-15",
      leaveBalance: 10,
      performanceReport: "Strong system architecture.",
    },
    {
      id: 38,
      name: "Julie Ross",
      email: "jross@example.com",
      position: "Quality Analyst",
      startDate: "2022-06-30",
      leaveBalance: 21,
      performanceReport: "Thorough quality assurance.",
    },
    {
      id: 39,
      name: "Howard Hughes",
      email: "hhughes@example.com",
      position: "Security Engineer",
      startDate: "2021-11-15",
      leaveBalance: 15,
      performanceReport: "Enhanced security measures.",
    },
    {
      id: 40,
      name: "Kathy Bennett",
      email: "kbennett@example.com",
      position: "Business Developer",
      startDate: "2022-03-15",
      leaveBalance: 18,
      performanceReport: "New business opportunities.",
    },
    {
      id: 41,
      name: "Arthur Gray",
      email: "agray@example.com",
      position: "Cloud Engineer",
      startDate: "2021-08-30",
      leaveBalance: 12,
      performanceReport: "Successful cloud migrations.",
    },
    {
      id: 42,
      name: "Virginia Hayes",
      email: "vhayes@example.com",
      position: "Research Analyst",
      startDate: "2022-07-20",
      leaveBalance: 20,
      performanceReport: "Detailed market research.",
    },
    {
      id: 43,
      name: "Lawrence Foster",
      email: "lfoster@example.com",
      position: "Mobile Developer",
      startDate: "2021-04-15",
      leaveBalance: 14,
      performanceReport: "Quality mobile solutions.",
    },
    {
      id: 44,
      name: "Alice Butler",
      email: "abutler@example.com",
      position: "Support Specialist",
      startDate: "2022-01-30",
      leaveBalance: 16,
      performanceReport: "Excellent customer support.",
    },
    {
      id: 45,
      name: "Peter Simmons",
      email: "psimmons@example.com",
      position: "Data Scientist",
      startDate: "2021-10-01",
      leaveBalance: 11,
      performanceReport: "Valuable data analysis.",
    },
    {
      id: 46,
      name: "Jean Bryant",
      email: "jbryant@example.com",
      position: "UI Designer",
      startDate: "2022-04-20",
      leaveBalance: 19,
      performanceReport: "Creative UI designs.",
    },
    {
      id: 47,
      name: "Bruce Russell",
      email: "brussell@example.com",
      position: "IT Manager",
      startDate: "2021-07-15",
      leaveBalance: 13,
      performanceReport: "Effective IT leadership.",
    },
    {
      id: 48,
      name: "Lois Griffin",
      email: "lgriffin@example.com",
      position: "Product Owner",
      startDate: "2022-02-10",
      leaveBalance: 17,
      performanceReport: "Strong product vision.",
    },
    {
      id: 49,
      name: "Wayne Kelly",
      email: "wkelly@example.com",
      position: "Full Stack Developer",
      startDate: "2021-05-01",
      leaveBalance: 10,
      performanceReport: "Versatile development skills.",
    },
    {
      id: 50,
      name: "Theresa Sanders",
      email: "tsanders@example.com",
      position: "Scrum Master",
      startDate: "2022-06-01",
      leaveBalance: 21,
      performanceReport: "Effective team facilitation.",
    }
  ];
  
  const employeeReducer = (state = initialEmployees, action) => {
    switch (action.type) {
      default:
        return state;
    }
  };
  
  export default employeeReducer;